import "./globals.css";
import { Wrapper } from "./wrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="h-full bg-white">
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
